#
#  Author: Hari Sekhon
#  Date: 2024-11-19 21:36:23 +0400 (Tue, 19 Nov 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/TamperMonkey
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                  E s L i n t
# ============================================================================ #

---
name: EsLint

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.js'
      - .github/workflows/eslint.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.js'
      - .github/workflows/eslint.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  EsLint:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: EsLint
    uses: HariSekhon/GitHub-Actions/.github/workflows/eslint.yaml@master
    with:
      submodules: false
      debug: ${{ github.event.inputs.debug }}
